version: "3.7"

services:
  django:
    build: ./backend
    container_name: taller-dashboard-django
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    volumes:
      - ./backend/:/srv/app
      - static:/srv/app/static
      - media:/srv/app/media
    depends_on:
      - db

    networks:
      - market_net

  react:
    build: ./frontend
    container_name: taller-dashboard-react
    command: yarn start
    ports:
      - 3000:3000
    env_file:
      - ./.env.dev
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_BASE_URL=http://172.0.0.1:8000
    volumes:
      - ./frontend/:/srv/app
      - /srv/app/node_modules
    depends_on:
      - django

    networks:
      - market_net

  db:
    image: postgres:16.3-alpine3.19
    container_name: taller-dashboard-db
    ports:
      - 5432:5432
    env_file: ./.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - market_net

  nginx:
    build: ./nginx
    container_name: taller-dashboard-nginx
    ports:
      - 8080:80
    restart: always
    volumes:
      - static:/srv/app/static
      - media:/srv/app/media
    depends_on:
      - django
      - react
      - db
    networks:
      - market_net

  tensorflow:
    build:
      context: ./tensorflow
    ports:
      - "5000:5000"
    volumes:
      - ./tensorflow/model.h5:/app/model.h5
    depends_on:
      - django
    networks:
      - market_net

volumes:
  postgres_data:
  media:
  static:
networks:
  market_net:
    driver: bridge